version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn cbrsite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on:
      - web    

volumes:
  postgres_data:
  static_volume:
  media_volume:
