# Generated by Django 3.1.6 on 2021-04-12 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20210410_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
