# Generated by Django 3.1.6 on 2021-04-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20210412_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
